#!/usr/bin/env bash
#MISE description="Run all tests"
#MISE depends=["test:completions", "test:doctor", "test:install", "test:list", "test:registry", "test:resolve", "test:shim", "test:uninstall", "test:update"]
